set schema 'oltp';

insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (1, 'Trilia', 'eabsalom0@4shared.com', 'Analog Circuit Design manager', '808 Raven Junction', 'Taverny', 'Île-de-France', '95251 CEDEX', 'France', '+33 523 256 2393', '+1 349 931 1907');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (2, 'Ooba', 'jaudas1@baidu.com', 'Product Engineer', '46011 Glendale Point', 'Bordeaux', 'Aquitaine', '33100', 'France', '+33 717 509 4086', '+86 136 910 1174');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (3, 'Trudoo', 'lkinrade2@webeden.co.uk', 'Office Assistant I', '3 Jackson Circle', 'Barreiro', 'Viana do Castelo', '4950-642', 'Portugal', '+351 999 749 8159', '+994 182 229 8766');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (4, 'Brainlounge', 'icords3@mozilla.com', 'Environmental Tech', '47 Evergreen Way', 'La Rochelle', 'Poitou-Charentes', '17024 CEDEX 1', 'France', '+33 798 601 7196', '+86 542 849 2781');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (5, 'Cogidoo', 'pmacaughtrie4@apple.com', 'Business Systems Development Analyst', '201 Monument Junction', 'Stuttgart', 'Baden-Württemberg', '70567', 'Germany', '+49 133 678 3526', '+64 447 170 4951');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (6, 'Brainverse', 'jalliban5@pagesperso-orange.fr', 'Social Worker', '36804 Summit Street', 'Hayange', 'Lorraine', '57704 CEDEX', 'France', '+33 333 151 4608', '+63 243 646 0498');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (7, 'Linkbuzz', 'eschohier6@dropbox.com', 'Account Representative IV', '159 Fisk Crossing', 'Noyon', 'Picardie', '60406 CEDEX', 'France', '+33 505 789 1419', '+55 706 898 5776');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (8, 'Fivechat', 'mmacneillie7@mtv.com', 'Dental Hygienist', '19269 Red Cloud Park', 'Évry', 'Île-de-France', '91024 CEDEX', 'France', '+33 975 271 6081', '+98 462 948 9456');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (9, 'Tanoodle', 'pcossor8@globo.com', 'Health Coach I', '311 Arrowood Center', 'Abelheira', 'Lisboa', '2530-063', 'Portugal', '+351 173 198 1495', '+375 226 565 1319');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (10, 'Eare', 'aivashinnikov9@webeden.co.uk', 'Dental Hygienist', '59 Sundown Road', 'Almada', 'Setúbal', '2800-011', 'Portugal', '+351 208 153 4178', '+7 498 903 1462');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (11, 'Brainverse', 'woniansa@dell.com', 'Environmental Specialist', '7379 Valley Edge Crossing', 'Berlin', 'Berlin', '12437', 'Germany', '+49 195 112 1408', '+92 956 237 1385');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (12, 'Skimia', 'cpottb@nifty.com', 'Food Chemist', '21 Hoffman Drive', 'Cabanas de Viriato', 'Viseu', '3430-605', 'Portugal', '+351 644 179 2010', '+55 137 260 1652');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (13, 'Dazzlesphere', 'tmacleesec@amazon.co.uk', 'General Manager', '1 Butternut Crossing', 'Cabeça Gorda', 'Lisboa', '2530-333', 'Portugal', '+351 711 170 4657', '+86 743 848 3529');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (14, 'Zoozzy', 'jdegoeyd@economist.com', 'Human Resources Assistant IV', '15 Anniversary Drive', 'Burgau', 'Faro', '8650-104', 'Portugal', '+351 244 372 8335', '+48 723 308 9358');
insert into supplier (supplier_id, company_name, contact_person, "position", address, city, region, postal_code, country, phone, fax) values (15, 'Yozio', 'apoteburye@indiegogo.com', 'Human Resources Assistant II', '21808 Sheridan Pass', 'Ponta Delgada', 'Ilha de São Miguel', '9500-014', 'Portugal', '+351 413 453 6343', '+55 844 272 6422');

insert into category (category_id, category_name, description) values (1, 'woodwork', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into category (category_id, category_name, description) values (2, 'toys', null);
insert into category (category_id, category_name, description) values (3, 'furniture', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into category (category_id, category_name, description) values (4, 'tools', 'Proin eu mi. Nulla ac enim.');
insert into category (category_id, category_name, description) values (5, 'vehicles', null);
insert into category (category_id, category_name, description) values (6, 'foods', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into category (category_id, category_name, description) values (7, 'outdoors', 'Aliquam non mauris. Morbi non lectus.');
insert into category (category_id, category_name, description) values (8, null, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into category (category_id, category_name, description) values (9, null, null);